# Generated by Django 4.2.7 on 2023-11-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cHub', '0002_club_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField(blank=True)),
                ('logo', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('isOnline', models.BooleanField()),
                ('organizingHead', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='cHub.student')),
            ],
        ),
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subEventID', models.CharField(max_length=4)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('logo', models.URLField(blank=True)),
                ('isOnline', models.BooleanField()),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Coordinator', to='cHub.student')),
                ('coreCoordinator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='CoreCoordinator', to='cHub.student')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eventCal.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.CharField(max_length=4)),
                ('sessionName', models.CharField(blank=True, max_length=20)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eventCal.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventCoreTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eventCal.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cHub.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subevent',
            constraint=models.UniqueConstraint(fields=('eventID', 'subEventID'), name='subEvent_primary_key_constraint'),
        ),
        migrations.AddConstraint(
            model_name='eventsession',
            constraint=models.UniqueConstraint(fields=('eventID', 'sessionID'), name='session_primary_key_constraint'),
        ),
        migrations.AddConstraint(
            model_name='eventcoreteam',
            constraint=models.UniqueConstraint(fields=('eventID', 'member'), name='coreTeam_primary_key_constraint'),
        ),
    ]
