# Generated by Django 4.2.7 on 2023-11-17 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cHub', '0003_clubmember_student_name_and_more'),
        ('eventCal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='location',
            field=models.CharField(default='nd', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EventOperationsTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=20)),
                ('coreCoordinator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cHub.student')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eventCal.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventOperationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Coordinator', 'Coordinator'), ('Volunteer', 'Volunteer')], default='Volunteer', max_length=11)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cHub.student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='eventCal.eventoperationsteam')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventoperationsteam',
            constraint=models.UniqueConstraint(fields=('eventID', 'teamID'), name='operations_primary_key_constraint'),
        ),
        migrations.AddConstraint(
            model_name='eventoperationmember',
            constraint=models.UniqueConstraint(fields=('team', 'member', 'role'), name='operationMember_primary_key_constraint'),
        ),
    ]
