# Generated by Django 4.2.7 on 2023-11-24 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cHub', '0005_alter_clubmember_role'),
        ('eventCal', '0003_event_name_event_repetition_eventsession_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoperationsteam',
            name='relatedClub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cHub.club'),
        ),
        migrations.DeleteModel(
            name='EventOperationMember',
        ),
    ]
