# Generated by Django 4.2.7 on 2023-11-15 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.PositiveIntegerField()),
                ('batch_no', models.PositiveIntegerField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cHub.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.CharField(max_length=10)),
                ('club_year', models.PositiveIntegerField()),
                ('club_name', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('faculty_mentor', models.CharField(max_length=50)),
                ('president_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='president', to='cHub.student')),
                ('vice_president_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vice_president', to='cHub.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('roll_no', 'branch_id', 'batch_no'), name='student_primary_key_constraint'),
        ),
    ]
