# Generated by Django 4.2.7 on 2023-11-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.URLField(blank=True),
        ),
    ]
