# Generated by Django 4.2.7 on 2023-11-17 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cHub', '0002_club_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Coordinator', 'Coordinator'), ('Volunteer', 'Volunteer')], default='Volunteer', max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='nd', max_length=30),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(fields=('club_id', 'club_year'), name='club_primary_key_constraint'),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='club_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cHub.club'),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cHub.student'),
        ),
        migrations.AddConstraint(
            model_name='clubmember',
            constraint=models.UniqueConstraint(fields=('club_id', 'member', 'role'), name='clubMember_primary_key_constraint'),
        ),
    ]
