# Generated by Django 4.2.7 on 2023-11-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cHub', '0003_clubmember_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='club',
            name='club_primary_key_constraint',
        ),
        migrations.AddField(
            model_name='club',
            name='faculty_mentor_picture',
            field=models.URLField(default='https://dummyimage.com/500&text=Image+not+Found'),
        ),
        migrations.AddField(
            model_name='club',
            name='president_picture',
            field=models.URLField(default='https://dummyimage.com/500&text=Image+not+Found'),
        ),
        migrations.AddField(
            model_name='club',
            name='vice_president_picture',
            field=models.URLField(default='https://dummyimage.com/500&text=Image+not+Found'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.URLField(default='https://dummyimage.com/500&text=Image+not+Found'),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(fields=('club_id', 'club_year', 'topic'), name='club_primary_key_constraint'),
        ),
    ]
