# Generated by Django 4.2.7 on 2023-11-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cHub', '0004_remove_club_club_primary_key_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='role',
            field=models.CharField(default='Volunteer', max_length=20),
        ),
    ]
